[tool]
[tool.pdm]

[project]
name = "nscap-sdn"
version = "0.1.0"
description = ""
authors = [{ name = "alan910127", email = "alan469357@gmail.com" }]
dependencies = [
    "eventlet==0.30.2",
    "wheel>=0.40.0",
    "ryu>=4.34",
]
requires-python = ">=3.8"
license = { text = "MIT" }
